/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2UserStatus } from './v2-user-status';

/**
 * 
 * @export
 * @interface AccountServiceUpdateUserStatusRequest
 */
export interface AccountServiceUpdateUserStatusRequest {
    /**
     * 
     * @type {V2UserStatus}
     * @memberof AccountServiceUpdateUserStatusRequest
     */
    'status': V2UserStatus;
    /**
     * The reason for the status change
     * @type {string}
     * @memberof AccountServiceUpdateUserStatusRequest
     */
    'reason'?: string;
}



