/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Approvalv2ApprovalStatus } from './approvalv2-approval-status';

/**
 * 
 * @export
 * @interface Approvalv2Approval
 */
export interface Approvalv2Approval {
    /**
     * The approval ID
     * @type {string}
     * @memberof Approvalv2Approval
     */
    'id': string;
    /**
     * The approval set ID
     * @type {string}
     * @memberof Approvalv2Approval
     */
    'approvalSetId': string;
    /**
     * The user ID
     * @type {string}
     * @memberof Approvalv2Approval
     */
    'userId': string;
    /**
     * The date and time the approval was created
     * @type {string}
     * @memberof Approvalv2Approval
     */
    'createdAt': string;
    /**
     * The date and time the approval was updated
     * @type {string}
     * @memberof Approvalv2Approval
     */
    'updatedAt': string;
    /**
     * The signed approval
     * @type {string}
     * @memberof Approvalv2Approval
     */
    'signature'?: string;
    /**
     * The reasons for an approval or rejection
     * @type {Array<string>}
     * @memberof Approvalv2Approval
     */
    'reasons': Array<string>;
    /**
     * 
     * @type {Approvalv2ApprovalStatus}
     * @memberof Approvalv2Approval
     */
    'status': Approvalv2ApprovalStatus;
}



