/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Approvalv2ApprovalStatus = {
    Processing: 'PROCESSING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;

export type Approvalv2ApprovalStatus = typeof Approvalv2ApprovalStatus[keyof typeof Approvalv2ApprovalStatus];



