/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Approvalv2ApprovalStatus } from './approvalv2-approval-status';

/**
 * 
 * @export
 * @interface ApprovalServiceUpdateApprovalRequest
 */
export interface ApprovalServiceUpdateApprovalRequest {
    /**
     * The approval signature
     * @type {string}
     * @memberof ApprovalServiceUpdateApprovalRequest
     */
    'signature'?: string;
    /**
     * The reasons for an approval or rejection
     * @type {Array<string>}
     * @memberof ApprovalServiceUpdateApprovalRequest
     */
    'reasons': Array<string>;
    /**
     * 
     * @type {Approvalv2ApprovalStatus}
     * @memberof ApprovalServiceUpdateApprovalRequest
     */
    'status': Approvalv2ApprovalStatus;
}



