/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Commonv2Address
 */
export interface Commonv2Address {
    /**
     * The first line of the address
     * @type {string}
     * @memberof Commonv2Address
     */
    'address1': string;
    /**
     * The second line of the address
     * @type {string}
     * @memberof Commonv2Address
     */
    'address2'?: string;
    /**
     * The city of the address
     * @type {string}
     * @memberof Commonv2Address
     */
    'city': string;
    /**
     * The state of the address
     * @type {string}
     * @memberof Commonv2Address
     */
    'state': string;
    /**
     * The postal code of the address
     * @type {string}
     * @memberof Commonv2Address
     */
    'postCode': string;
    /**
     * The country of the address
     * @type {string}
     * @memberof Commonv2Address
     */
    'country': string;
}

