/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2AddressDetails } from './v2-address-details';
// May contain unused imports in some cases
// @ts-ignore
import type { V2Custodian } from './v2-custodian';

/**
 * 
 * @export
 * @interface CounterpartyServiceCreateAddressRequest
 */
export interface CounterpartyServiceCreateAddressRequest {
    /**
     * 
     * @type {V2Custodian}
     * @memberof CounterpartyServiceCreateAddressRequest
     */
    'custodian'?: V2Custodian;
    /**
     * Whether the user has accepted the terms and conditions
     * @type {boolean}
     * @memberof CounterpartyServiceCreateAddressRequest
     */
    'termsAndConditionsAccepted': boolean;
    /**
     * 
     * @type {V2AddressDetails}
     * @memberof CounterpartyServiceCreateAddressRequest
     */
    'details': V2AddressDetails;
}

