/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Identityv1TransactionStatus = {
    TransactionCreated: 'TRANSACTION_CREATED',
    TransactionApproved: 'TRANSACTION_APPROVED',
    TransactionSigned: 'TRANSACTION_SIGNED',
    TransactionPublished: 'TRANSACTION_PUBLISHED',
    TransactionConfirmed: 'TRANSACTION_CONFIRMED',
    TransactionFailed: 'TRANSACTION_FAILED'
} as const;

export type Identityv1TransactionStatus = typeof Identityv1TransactionStatus[keyof typeof Identityv1TransactionStatus];



