/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Identityv1WalletStatus = {
    Created: 'CREATED',
    Provisioning: 'PROVISIONING',
    Provisioned: 'PROVISIONED',
    ProvisioningFailed: 'PROVISIONING_FAILED'
} as const;

export type Identityv1WalletStatus = typeof Identityv1WalletStatus[keyof typeof Identityv1WalletStatus];



