/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Note for reviewer: we wanted to not have the gateway depend on the approval service, so we redeclare these messages and map.
 * @export
 * @enum {string}
 */

export const Identityv1ApprovalStatus = {
    Processing: 'PROCESSING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;

export type Identityv1ApprovalStatus = typeof Identityv1ApprovalStatus[keyof typeof Identityv1ApprovalStatus];



