/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Identityv1Approval } from './identityv1-approval';
// May contain unused imports in some cases
// @ts-ignore
import type { Identityv1Summary } from './identityv1-summary';

/**
 * 
 * @export
 * @interface Identityv1ApprovalSummary
 */
export interface Identityv1ApprovalSummary {
    /**
     * 
     * @type {Identityv1Approval}
     * @memberof Identityv1ApprovalSummary
     */
    'approval'?: Identityv1Approval;
    /**
     * 
     * @type {Identityv1Summary}
     * @memberof Identityv1ApprovalSummary
     */
    'summary'?: Identityv1Summary;
}

