/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Identityv1ApprovalSetStatus } from './identityv1-approval-set-status';
// May contain unused imports in some cases
// @ts-ignore
import type { V1SummarySourceType } from './v1-summary-source-type';

/**
 * 
 * @export
 * @interface Identityv1Summary
 */
export interface Identityv1Summary {
    /**
     * 
     * @type {string}
     * @memberof Identityv1Summary
     */
    'sourceId'?: string;
    /**
     * 
     * @type {V1SummarySourceType}
     * @memberof Identityv1Summary
     */
    'sourceType'?: V1SummarySourceType;
    /**
     * 
     * @type {string}
     * @memberof Identityv1Summary
     */
    'sourceRaw'?: string;
    /**
     * 
     * @type {string}
     * @memberof Identityv1Summary
     */
    'expiresAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Identityv1Summary
     */
    'metAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof Identityv1Summary
     */
    'currentApprovedCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Identityv1Summary
     */
    'requiredApproverCount'?: number;
    /**
     * 
     * @type {Identityv1ApprovalSetStatus}
     * @memberof Identityv1Summary
     */
    'status'?: Identityv1ApprovalSetStatus;
}



