/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegistryManagementServiceManagementUpdateAssetRequest
 */
export interface RegistryManagementServiceManagementUpdateAssetRequest {
    /**
     * Updated asset name
     * @type {string}
     * @memberof RegistryManagementServiceManagementUpdateAssetRequest
     */
    'name'?: string;
    /**
     * Updated decimal places
     * @type {number}
     * @memberof RegistryManagementServiceManagementUpdateAssetRequest
     */
    'decimals'?: number;
    /**
     * Updated CoinGecko identifier
     * @type {string}
     * @memberof RegistryManagementServiceManagementUpdateAssetRequest
     */
    'coingeckoId'?: string;
    /**
     * Updated enabled status
     * @type {boolean}
     * @memberof RegistryManagementServiceManagementUpdateAssetRequest
     */
    'enabled'?: boolean;
    /**
     * Updated vetted status
     * @type {boolean}
     * @memberof RegistryManagementServiceManagementUpdateAssetRequest
     */
    'vetted'?: boolean;
}

