/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2BlockchainStatus } from './v2-blockchain-status';

/**
 * 
 * @export
 * @interface RegistryManagementServiceManagementUpdateBlockchainRequest
 */
export interface RegistryManagementServiceManagementUpdateBlockchainRequest {
    /**
     * Updated blockchain name
     * @type {string}
     * @memberof RegistryManagementServiceManagementUpdateBlockchainRequest
     */
    'name'?: string;
    /**
     * Updated namespace
     * @type {string}
     * @memberof RegistryManagementServiceManagementUpdateBlockchainRequest
     */
    'namespace'?: string;
    /**
     * Updated chain identifier
     * @type {string}
     * @memberof RegistryManagementServiceManagementUpdateBlockchainRequest
     */
    'chain'?: string;
    /**
     * Updated chain ID
     * @type {string}
     * @memberof RegistryManagementServiceManagementUpdateBlockchainRequest
     */
    'chainId'?: string;
    /**
     * Updated routing configuration
     * @type {string}
     * @memberof RegistryManagementServiceManagementUpdateBlockchainRequest
     */
    'routing'?: string;
    /**
     * 
     * @type {V2BlockchainStatus}
     * @memberof RegistryManagementServiceManagementUpdateBlockchainRequest
     */
    'status'?: V2BlockchainStatus;
    /**
     * Updated WalletConnect support
     * @type {boolean}
     * @memberof RegistryManagementServiceManagementUpdateBlockchainRequest
     */
    'supportsWalletConnect'?: boolean;
}



