/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Transactionsv2CurrencyAmount } from './transactionsv2-currency-amount';

/**
 * 
 * @export
 * @interface TransactionsServiceSubmitClawbackRequest
 */
export interface TransactionsServiceSubmitClawbackRequest {
    /**
     * 
     * @type {Transactionsv2CurrencyAmount}
     * @memberof TransactionsServiceSubmitClawbackRequest
     */
    'amount': Transactionsv2CurrencyAmount;
    /**
     * Optional holder address for MPTokens
     * @type {string}
     * @memberof TransactionsServiceSubmitClawbackRequest
     */
    'holder'?: string;
    /**
     * The blockchain nonce/sequence to use
     * @type {string}
     * @memberof TransactionsServiceSubmitClawbackRequest
     */
    'sequence'?: string;
    /**
     * Highest ledger index this transaction can appear in.
     * @type {string}
     * @memberof TransactionsServiceSubmitClawbackRequest
     */
    'lastLedgerSequence'?: string;
    /**
     * Source tag to use for this transaction
     * @type {string}
     * @memberof TransactionsServiceSubmitClawbackRequest
     */
    'sourceTag'?: string;
}

