/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Transactionsv2AccountSetFlag = {
    AccountTxnId: 'ACCOUNT_TXN_ID',
    AllowTrustlineClawback: 'ALLOW_TRUSTLINE_CLAWBACK',
    AuthzNftokenMinter: 'AUTHZ_NFTOKEN_MINTER',
    DefaultRipple: 'DEFAULT_RIPPLE',
    DepositAuth: 'DEPOSIT_AUTH',
    DisableMaster: 'DISABLE_MASTER',
    DisallowIncomingCheck: 'DISALLOW_INCOMING_CHECK',
    DisallowIncomingPayChan: 'DISALLOW_INCOMING_PAY_CHAN',
    DisallowIncomingTrustline: 'DISALLOW_INCOMING_TRUSTLINE',
    DisallowXrp: 'DISALLOW_XRP',
    GlobalFreeze: 'GLOBAL_FREEZE',
    NoFreeze: 'NO_FREEZE',
    RequireAuth: 'REQUIRE_AUTH',
    RequireDest: 'REQUIRE_DEST'
} as const;

export type Transactionsv2AccountSetFlag = typeof Transactionsv2AccountSetFlag[keyof typeof Transactionsv2AccountSetFlag];



