/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Transactionsv2OfferCreateFlags = {
    Passive: 'PASSIVE',
    ImmediateOrCancel: 'IMMEDIATE_OR_CANCEL',
    FillOrKill: 'FILL_OR_KILL',
    Sell: 'SELL'
} as const;

export type Transactionsv2OfferCreateFlags = typeof Transactionsv2OfferCreateFlags[keyof typeof Transactionsv2OfferCreateFlags];



