/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Transactionsv2AddressType } from './transactionsv2-address-type';

/**
 * 
 * @export
 * @interface Transactionsv2Address
 */
export interface Transactionsv2Address {
    /**
     * Either addressID or walletID, or allowAddressID, or not set when the address does not exist within palisade e.g. a deposit from outside of Palisade
     * @type {string}
     * @memberof Transactionsv2Address
     */
    'id'?: string;
    /**
     * The organization ID
     * @type {string}
     * @memberof Transactionsv2Address
     */
    'organizationId'?: string;
    /**
     * The counterparty ID
     * @type {string}
     * @memberof Transactionsv2Address
     */
    'counterpartyId'?: string;
    /**
     * The vault ID
     * @type {string}
     * @memberof Transactionsv2Address
     */
    'vaultId'?: string;
    /**
     * 
     * @type {Transactionsv2AddressType}
     * @memberof Transactionsv2Address
     */
    'type': Transactionsv2AddressType;
    /**
     * The address
     * @type {string}
     * @memberof Transactionsv2Address
     */
    'address': string;
}



