/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Transactionsv2AccountSetFlag } from './transactionsv2-account-set-flag';

/**
 * 
 * @export
 * @interface TransactionsServiceSubmitAccountSetRequest
 */
export interface TransactionsServiceSubmitAccountSetRequest {
    /**
     * 
     * @type {Transactionsv2AccountSetFlag}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'setFlag'?: Transactionsv2AccountSetFlag;
    /**
     * 
     * @type {Transactionsv2AccountSetFlag}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'clearFlag'?: Transactionsv2AccountSetFlag;
    /**
     * Hex encoded string representing domain that owns this account in ASCII, less than 256 chars. Set empty to unset.
     * @type {string}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'domain'?: string;
    /**
     * Hex encoded 128-bit hash bytes of the email address representing this account. Set empty to unset.
     * @type {string}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'emailHash'?: string;
    /**
     * 33-byte public key for sending encrypted messages to this account. First byte must be one of (0x02, 0x03, 0xED). Set empty to unset.
     * @type {string}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'messageKey'?: string;
    /**
     * Address of another account that can mint NFTokens for this account
     * @type {string}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'nfTokenMinter'?: string;
    /**
     * Fee to charge when users transfer tokens issued by this account, represented as billionths of a unit between 1000000000 and 2000000000 or 0.
     * @type {number}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'transferRate'?: number;
    /**
     * Tick size to use for offers involving a currency issued by this address, must be 3 to 15 (inclusive) or 0
     * @type {number}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'tickSize'?: number;
    /**
     * An arbitrary 256-bit hash value to associate with this account
     * @type {string}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'walletLocator'?: string;
    /**
     * Unused field to associate on the account
     * @type {number}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'walletSize'?: number;
    /**
     * The blockchain nonce/sequence to use
     * @type {string}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'sequence'?: string;
    /**
     * Highest ledger index this transaction can appear in.
     * @type {string}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'lastLedgerSequence'?: string;
    /**
     * Source tag to use for this transaction
     * @type {string}
     * @memberof TransactionsServiceSubmitAccountSetRequest
     */
    'sourceTag'?: string;
}



