/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Transactionsv2CurrencyAmount
 */
export interface Transactionsv2CurrencyAmount {
    /**
     * The quantity of the asset
     * @type {string}
     * @memberof Transactionsv2CurrencyAmount
     */
    'value': string;
    /**
     * The asset symbol
     * @type {string}
     * @memberof Transactionsv2CurrencyAmount
     */
    'asset': string;
    /**
     * The contract/issuing address. Optional if asset is XRP.
     * @type {string}
     * @memberof Transactionsv2CurrencyAmount
     */
    'issuer'?: string;
}

