/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionsServiceRawTransactionRequest
 */
export interface TransactionsServiceRawTransactionRequest {
    /**
     * The encoded transaction. Note that this must be encoded in the relevant blockchain format. RLP encoded for EVM chains. Binary codec encoding for XRP.
     * @type {string}
     * @memberof TransactionsServiceRawTransactionRequest
     */
    'encodedTransaction': string;
    /**
     * Whether to only sign the transaction, or also publish it to the blockchain
     * @type {boolean}
     * @memberof TransactionsServiceRawTransactionRequest
     */
    'signOnly': boolean;
}

