/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V1SummarySourceType = {
    Transaction: 'TRANSACTION',
    Device: 'DEVICE'
} as const;

export type V1SummarySourceType = typeof V1SummarySourceType[keyof typeof V1SummarySourceType];



