/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2VaultTag } from './v2-vault-tag';

/**
 * Contains the updated list of tags for the vault.
 * @export
 * @interface V2AddVaultTagResponse
 */
export interface V2AddVaultTagResponse {
    /**
     * 
     * @type {Array<V2VaultTag>}
     * @memberof V2AddVaultTagResponse
     */
    'tags'?: Array<V2VaultTag>;
}

