/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2SourceType } from './v2-source-type';

/**
 * 
 * @export
 * @interface V2ApprovalGroup
 */
export interface V2ApprovalGroup {
    /**
     * A list of users in the approval group
     * @type {Array<string>}
     * @memberof V2ApprovalGroup
     */
    'approvers': Array<string>;
    /**
     * The required approver count
     * @type {number}
     * @memberof V2ApprovalGroup
     */
    'requiredApproverCount': number;
    /**
     * 
     * @type {V2SourceType}
     * @memberof V2ApprovalGroup
     */
    'sourceType': V2SourceType;
}



