/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Commonv2Asset } from './commonv2-asset';

/**
 * 
 * @export
 * @interface V2Balance
 */
export interface V2Balance {
    /**
     * 
     * @type {Commonv2Asset}
     * @memberof V2Balance
     */
    'asset'?: Commonv2Asset;
    /**
     * The total balance of the asset on the blockchain. When breakdown fields are present, this equals available_balance + pending_balance + frozen_balance
     * @type {string}
     * @memberof V2Balance
     */
    'balance'?: string;
    /**
     * The exchange rate between the asset and \'currencyCode\'
     * @type {string}
     * @memberof V2Balance
     */
    'rate'?: string;
    /**
     * The aggregated fiat value of an asset for a wallet
     * @type {string}
     * @memberof V2Balance
     */
    'fiatValue'?: string;
    /**
     * The available balance that can be spent
     * @type {string}
     * @memberof V2Balance
     */
    'availableBalance'?: string;
    /**
     * The balance tied up in pending transactions
     * @type {string}
     * @memberof V2Balance
     */
    'pendingBalance'?: string;
    /**
     * The balance frozen by policy actions
     * @type {string}
     * @memberof V2Balance
     */
    'frozenBalance'?: string;
}

