/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V2Blockchain = {
    Avalanche: 'AVALANCHE',
    Ethereum: 'ETHEREUM',
    XrpLedger: 'XRP_LEDGER',
    Polygon: 'POLYGON',
    Bnbchain: 'BNBCHAIN',
    Base: 'BASE',
    Hedera: 'HEDERA',
    Arbitrum: 'ARBITRUM',
    OneMoney: 'ONE_MONEY',
    Solana: 'SOLANA',
    Tron: 'TRON',
    Bitcoin: 'BITCOIN'
} as const;

export type V2Blockchain = typeof V2Blockchain[keyof typeof V2Blockchain];



