/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2CreateRecoveryPublicKeyRequest } from './v2-create-recovery-public-key-request';
// May contain unused imports in some cases
// @ts-ignore
import type { V2S3Config } from './v2-s3-config';

/**
 * 
 * @export
 * @interface V2CreateBackupStrategyRequest
 */
export interface V2CreateBackupStrategyRequest {
    /**
     * Name of the backup strategy (2-64 characters)
     * @type {string}
     * @memberof V2CreateBackupStrategyRequest
     */
    'name'?: string;
    /**
     * List of backup keys - DER formatted, hex encoded RSA public keys (min 4096 bits)
     * @type {Array<V2CreateRecoveryPublicKeyRequest>}
     * @memberof V2CreateBackupStrategyRequest
     */
    'recoveryPublicKeys'?: Array<V2CreateRecoveryPublicKeyRequest>;
    /**
     * 
     * @type {V2S3Config}
     * @memberof V2CreateBackupStrategyRequest
     */
    's3Config'?: V2S3Config;
}

