/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V2ConflictReport
 */
export interface V2ConflictReport {
    /**
     * ID of the asset with conflict
     * @type {string}
     * @memberof V2ConflictReport
     */
    'assetId'?: string;
    /**
     * Source of existing asset data
     * @type {string}
     * @memberof V2ConflictReport
     */
    'existingSource'?: string;
    /**
     * Source of new asset data
     * @type {string}
     * @memberof V2ConflictReport
     */
    'newSource'?: string;
    /**
     * How the conflict was resolved
     * @type {string}
     * @memberof V2ConflictReport
     */
    'resolution'?: string;
    /**
     * Reason for the resolution
     * @type {string}
     * @memberof V2ConflictReport
     */
    'reason'?: string;
}

