/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2QuorumType } from './v2-quorum-type';

/**
 * 
 * @export
 * @interface V2CreateQuorumRequest
 */
export interface V2CreateQuorumRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof V2CreateQuorumRequest
     */
    'deviceIds': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V2CreateQuorumRequest
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof V2CreateQuorumRequest
     */
    'requiredSigners': number;
    /**
     * 
     * @type {string}
     * @memberof V2CreateQuorumRequest
     */
    'description'?: string;
    /**
     * 
     * @type {V2QuorumType}
     * @memberof V2CreateQuorumRequest
     */
    'quorumType': V2QuorumType;
    /**
     * 
     * @type {string}
     * @memberof V2CreateQuorumRequest
     */
    'backupStrategyId'?: string;
}



