/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2BoolFilter } from './v2-bool-filter';
// May contain unused imports in some cases
// @ts-ignore
import type { V2StringFilter } from './v2-string-filter';

/**
 * 
 * @export
 * @interface V2CurrencyFilter
 */
export interface V2CurrencyFilter {
    /**
     * 
     * @type {V2BoolFilter}
     * @memberof V2CurrencyFilter
     */
    'enabled'?: V2BoolFilter;
    /**
     * 
     * @type {V2StringFilter}
     * @memberof V2CurrencyFilter
     */
    'name'?: V2StringFilter;
    /**
     * 
     * @type {V2StringFilter}
     * @memberof V2CurrencyFilter
     */
    'code'?: V2StringFilter;
    /**
     * 
     * @type {V2StringFilter}
     * @memberof V2CurrencyFilter
     */
    'symbol'?: V2StringFilter;
}

