/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2DeviceType } from './v2-device-type';

/**
 * 
 * @export
 * @interface V2CreateDeviceRequest
 */
export interface V2CreateDeviceRequest {
    /**
     * The name of the device
     * @type {string}
     * @memberof V2CreateDeviceRequest
     */
    'displayName': string;
    /**
     * 
     * @type {V2DeviceType}
     * @memberof V2CreateDeviceRequest
     */
    'deviceType': V2DeviceType;
}



