/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2Category } from './v2-category';

/**
 * 
 * @export
 * @interface V2CreateCredentialRequest
 */
export interface V2CreateCredentialRequest {
    /**
     * A helpful name to help identify the credentials
     * @type {string}
     * @memberof V2CreateCredentialRequest
     */
    'name': string;
    /**
     * A helpful description to help identify the credentials
     * @type {string}
     * @memberof V2CreateCredentialRequest
     */
    'description'?: string;
    /**
     * 
     * @type {V2Category}
     * @memberof V2CreateCredentialRequest
     */
    'category': V2Category;
    /**
     * The permissions that the credential will have
     * @type {Array<string>}
     * @memberof V2CreateCredentialRequest
     */
    'permissions': Array<string>;
    /**
     * List of IP addresses (in IP address or CIDR notation) that the credential is allowed to use
     * @type {Array<string>}
     * @memberof V2CreateCredentialRequest
     */
    'allowedIps'?: Array<string>;
}



