/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V2CreateWebhookRequest
 */
export interface V2CreateWebhookRequest {
    /**
     * The webhook name.
     * @type {string}
     * @memberof V2CreateWebhookRequest
     */
    'name': string;
    /**
     * The webhook description.
     * @type {string}
     * @memberof V2CreateWebhookRequest
     */
    'description'?: string;
    /**
     * The webhook endpoint to send data to
     * @type {string}
     * @memberof V2CreateWebhookRequest
     */
    'endpoint': string;
}

