/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2MatcherType } from './v2-matcher-type';

/**
 * 
 * @export
 * @interface V2Destination
 */
export interface V2Destination {
    /**
     * The destination ID
     * @type {string}
     * @memberof V2Destination
     */
    'id': string;
    /**
     * 
     * @type {V2MatcherType}
     * @memberof V2Destination
     */
    'matcherType': V2MatcherType;
}



