/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V2Explorer
 */
export interface V2Explorer {
    /**
     * Name of the explorer
     * @type {string}
     * @memberof V2Explorer
     */
    'name': string;
    /**
     * Base URL of the explorer
     * @type {string}
     * @memberof V2Explorer
     */
    'url': string;
    /**
     * URL format for transaction links (use {txHash} as placeholder)
     * @type {string}
     * @memberof V2Explorer
     */
    'transactionFormat': string;
    /**
     * URL format for address links (use {address} as placeholder)
     * @type {string}
     * @memberof V2Explorer
     */
    'addressFormat': string;
}

