/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2FreezeAction } from './v2-freeze-action';
// May contain unused imports in some cases
// @ts-ignore
import type { V2FreezeType } from './v2-freeze-type';

/**
 * 
 * @export
 * @interface V2FreezeHistoryEntry
 */
export interface V2FreezeHistoryEntry {
    /**
     * Unique identifier for this history entry
     * @type {string}
     * @memberof V2FreezeHistoryEntry
     */
    'id'?: string;
    /**
     * 
     * @type {V2FreezeAction}
     * @memberof V2FreezeHistoryEntry
     */
    'action'?: V2FreezeAction;
    /**
     * Reason for the freeze or unfreeze action
     * @type {string}
     * @memberof V2FreezeHistoryEntry
     */
    'reason'?: string;
    /**
     * User who performed the action (empty for automatic actions)
     * @type {string}
     * @memberof V2FreezeHistoryEntry
     */
    'userId'?: string;
    /**
     * Organization of the user who performed the action (empty for automatic actions)
     * @type {string}
     * @memberof V2FreezeHistoryEntry
     */
    'organizationId'?: string;
    /**
     * Timestamp when the action was performed
     * @type {string}
     * @memberof V2FreezeHistoryEntry
     */
    'performedAt'?: string;
    /**
     * 
     * @type {V2FreezeType}
     * @memberof V2FreezeHistoryEntry
     */
    'freezeType'?: V2FreezeType;
    /**
     * Risk score that triggered auto-freeze (0-100)
     * @type {number}
     * @memberof V2FreezeHistoryEntry
     */
    'riskScore'?: number;
}



