/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2EvmFeeEstimate } from './v2-evm-fee-estimate';

/**
 * 
 * @export
 * @interface V2FeeEstimate
 */
export interface V2FeeEstimate {
    /**
     * 
     * @type {V2EvmFeeEstimate}
     * @memberof V2FeeEstimate
     */
    'evm'?: V2EvmFeeEstimate;
    /**
     * Map of fee options where keys are fee types (slowest, slow, medium, fast, fastest) and values are the fee amounts in base asset units
     * @type {{ [key: string]: string; }}
     * @memberof V2FeeEstimate
     */
    'networkFees': { [key: string]: string; };
}

