/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V2FreezeAction = {
    FreezeActionFreeze: 'FREEZE_ACTION_FREEZE',
    FreezeActionUnfreeze: 'FREEZE_ACTION_UNFREEZE'
} as const;

export type V2FreezeAction = typeof V2FreezeAction[keyof typeof V2FreezeAction];



