/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2MQCredentials } from './v2-mqcredentials';

/**
 * 
 * @export
 * @interface V2GetDeviceCredentialsResponse
 */
export interface V2GetDeviceCredentialsResponse {
    /**
     * 
     * @type {V2MQCredentials}
     * @memberof V2GetDeviceCredentialsResponse
     */
    'mqCredentials'?: V2MQCredentials;
}

