/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Accountv2Organization } from './accountv2-organization';

/**
 * 
 * @export
 * @interface V2GetOrganizationResponse
 */
export interface V2GetOrganizationResponse {
    /**
     * 
     * @type {Accountv2Organization}
     * @memberof V2GetOrganizationResponse
     */
    'organization'?: Accountv2Organization;
}

