/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2PairingCredentials } from './v2-pairing-credentials';

/**
 * 
 * @export
 * @interface V2GetDevicePairingCredentialsResponse
 */
export interface V2GetDevicePairingCredentialsResponse {
    /**
     * 
     * @type {V2PairingCredentials}
     * @memberof V2GetDevicePairingCredentialsResponse
     */
    'pairingCredentials'?: V2PairingCredentials;
}

