/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2ConflictReport } from './v2-conflict-report';

/**
 * 
 * @export
 * @interface V2Import
 */
export interface V2Import {
    /**
     * Unique identifier for this import
     * @type {string}
     * @memberof V2Import
     */
    'importId'?: string;
    /**
     * Import batch identifier
     * @type {string}
     * @memberof V2Import
     */
    'batchId'?: string;
    /**
     * Source of the import (e.g., \'coingecko\')
     * @type {string}
     * @memberof V2Import
     */
    'source'?: string;
    /**
     * Current status of the import
     * @type {string}
     * @memberof V2Import
     */
    'status'?: string;
    /**
     * User or system that triggered the import
     * @type {string}
     * @memberof V2Import
     */
    'triggeredBy'?: string;
    /**
     * Whether this was a dry-run
     * @type {boolean}
     * @memberof V2Import
     */
    'dryRun'?: boolean;
    /**
     * When the import started
     * @type {string}
     * @memberof V2Import
     */
    'startedAt'?: string;
    /**
     * When the import completed
     * @type {string}
     * @memberof V2Import
     */
    'completedAt'?: string;
    /**
     * Total number of items processed
     * @type {number}
     * @memberof V2Import
     */
    'totalProcessed'?: number;
    /**
     * Number of new assets created
     * @type {number}
     * @memberof V2Import
     */
    'newAssets'?: number;
    /**
     * Number of assets updated
     * @type {number}
     * @memberof V2Import
     */
    'updatedAssets'?: number;
    /**
     * Number of failed assets
     * @type {number}
     * @memberof V2Import
     */
    'failedAssets'?: number;
    /**
     * Conflicts encountered during import
     * @type {Array<V2ConflictReport>}
     * @memberof V2Import
     */
    'conflicts'?: Array<V2ConflictReport>;
    /**
     * Error message if import failed
     * @type {string}
     * @memberof V2Import
     */
    'errorMessage'?: string;
}

