/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Commonv2Asset } from './commonv2-asset';

/**
 * 
 * @export
 * @interface V2InternalGetAssetResponse
 */
export interface V2InternalGetAssetResponse {
    /**
     * 
     * @type {Commonv2Asset}
     * @memberof V2InternalGetAssetResponse
     */
    'asset'?: Commonv2Asset;
}

