/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Counterpartyv2Address } from './counterpartyv2-address';
// May contain unused imports in some cases
// @ts-ignore
import type { V2Counterparty } from './v2-counterparty';

/**
 * 
 * @export
 * @interface V2InternalLookupAddressResponse
 */
export interface V2InternalLookupAddressResponse {
    /**
     * 
     * @type {V2Counterparty}
     * @memberof V2InternalLookupAddressResponse
     */
    'counterparty'?: V2Counterparty;
    /**
     * 
     * @type {Counterpartyv2Address}
     * @memberof V2InternalLookupAddressResponse
     */
    'address'?: Counterpartyv2Address;
}

