/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2Vault } from './v2-vault';

/**
 * 
 * @export
 * @interface V2InternalListVaultsResponse
 */
export interface V2InternalListVaultsResponse {
    /**
     * 
     * @type {Array<V2Vault>}
     * @memberof V2InternalListVaultsResponse
     */
    'vaults'?: Array<V2Vault>;
}

