/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Counterpartyv2Address } from './counterpartyv2-address';
// May contain unused imports in some cases
// @ts-ignore
import type { V2FilterResponse } from './v2-filter-response';

/**
 * 
 * @export
 * @interface V2ListAddressesResponse
 */
export interface V2ListAddressesResponse {
    /**
     * 
     * @type {V2FilterResponse}
     * @memberof V2ListAddressesResponse
     */
    'filter'?: V2FilterResponse;
    /**
     * 
     * @type {Array<Counterpartyv2Address>}
     * @memberof V2ListAddressesResponse
     */
    'addresses'?: Array<Counterpartyv2Address>;
}

