/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2UserAuthMethod } from './v2-user-auth-method';

/**
 * 
 * @export
 * @interface V2ListUserAuthMethodsResponse
 */
export interface V2ListUserAuthMethodsResponse {
    /**
     * 
     * @type {Array<V2UserAuthMethod>}
     * @memberof V2ListUserAuthMethodsResponse
     */
    'authMethods'?: Array<V2UserAuthMethod>;
}

