/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2SessionSet } from './v2-session-set';

/**
 * 
 * @export
 * @interface V2ListSessionSetsResponse
 */
export interface V2ListSessionSetsResponse {
    /**
     * 
     * @type {Array<V2SessionSet>}
     * @memberof V2ListSessionSetsResponse
     */
    'sessionSets'?: Array<V2SessionSet>;
}

