/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2CurrencyFilter } from './v2-currency-filter';
// May contain unused imports in some cases
// @ts-ignore
import type { V2PaginationRequest } from './v2-pagination-request';
// May contain unused imports in some cases
// @ts-ignore
import type { V2SearchQuery } from './v2-search-query';

/**
 * 
 * @export
 * @interface V2ListCurrenciesRequest
 */
export interface V2ListCurrenciesRequest {
    /**
     * 
     * @type {V2CurrencyFilter}
     * @memberof V2ListCurrenciesRequest
     */
    'filter'?: V2CurrencyFilter;
    /**
     * 
     * @type {V2SearchQuery}
     * @memberof V2ListCurrenciesRequest
     */
    'search'?: V2SearchQuery;
    /**
     * 
     * @type {V2PaginationRequest}
     * @memberof V2ListCurrenciesRequest
     */
    'pagination'?: V2PaginationRequest;
}

