/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2WalletTag } from './v2-wallet-tag';

/**
 * 
 * @export
 * @interface V2ListWalletTagsResponse
 */
export interface V2ListWalletTagsResponse {
    /**
     * 
     * @type {Array<V2WalletTag>}
     * @memberof V2ListWalletTagsResponse
     */
    'tags'?: Array<V2WalletTag>;
}

