/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2FilterResponse } from './v2-filter-response';
// May contain unused imports in some cases
// @ts-ignore
import type { V2SweepInstance } from './v2-sweep-instance';

/**
 * 
 * @export
 * @interface V2ListSweepInstancesResponse
 */
export interface V2ListSweepInstancesResponse {
    /**
     * 
     * @type {V2FilterResponse}
     * @memberof V2ListSweepInstancesResponse
     */
    'filter'?: V2FilterResponse;
    /**
     * The list of sweep instances with metadata
     * @type {Array<V2SweepInstance>}
     * @memberof V2ListSweepInstancesResponse
     */
    'sweepInstances'?: Array<V2SweepInstance>;
}

