/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - MEMBERSHIP_STATE_CREATED: Freshly created, but no push notification sent   - MEMBERSHIP_STATE_PENDING: Push notification to member device sent, but not received public key yet  - MEMBERSHIP_STATE_CONFIRMED: Device has confirmed with a public key  - MEMBERSHIP_STATE_REJECTED: Device has rejected membership  - MEMBERSHIP_STATE_FAILED: Generic error state  - MEMBERSHIP_STATE_SUPER: FSM USE ONLY: Super state  - MEMBERSHIP_STATE_INITIAL: FSM USE ONLY: Initial state
 * @export
 * @enum {string}
 */

export const V2MembershipState = {
    MembershipStateCreated: 'MEMBERSHIP_STATE_CREATED',
    MembershipStatePending: 'MEMBERSHIP_STATE_PENDING',
    MembershipStateConfirmed: 'MEMBERSHIP_STATE_CONFIRMED',
    MembershipStateRejected: 'MEMBERSHIP_STATE_REJECTED',
    MembershipStateFailed: 'MEMBERSHIP_STATE_FAILED',
    MembershipStateSuper: 'MEMBERSHIP_STATE_SUPER',
    MembershipStateInitial: 'MEMBERSHIP_STATE_INITIAL'
} as const;

export type V2MembershipState = typeof V2MembershipState[keyof typeof V2MembershipState];



