/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V2ManagementGetSyncStatusResponse
 */
export interface V2ManagementGetSyncStatusResponse {
    /**
     * Whether sync is enabled
     * @type {boolean}
     * @memberof V2ManagementGetSyncStatusResponse
     */
    'enabled'?: boolean;
    /**
     * Whether sync is currently running
     * @type {boolean}
     * @memberof V2ManagementGetSyncStatusResponse
     */
    'running'?: boolean;
    /**
     * Cron schedule for automatic sync
     * @type {string}
     * @memberof V2ManagementGetSyncStatusResponse
     */
    'schedule'?: string;
    /**
     * Next scheduled sync time
     * @type {string}
     * @memberof V2ManagementGetSyncStatusResponse
     */
    'nextRun'?: string;
    /**
     * Whether dry-run mode is enabled
     * @type {boolean}
     * @memberof V2ManagementGetSyncStatusResponse
     */
    'dryRun'?: boolean;
    /**
     * Batch size for processing
     * @type {number}
     * @memberof V2ManagementGetSyncStatusResponse
     */
    'batchSize'?: number;
}

