/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2Currency } from './v2-currency';

/**
 * 
 * @export
 * @interface V2ManagementUpdateCurrencyResponse
 */
export interface V2ManagementUpdateCurrencyResponse {
    /**
     * 
     * @type {V2Currency}
     * @memberof V2ManagementUpdateCurrencyResponse
     */
    'currency'?: V2Currency;
}

