/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2Blockchain } from './v2-blockchain';
// May contain unused imports in some cases
// @ts-ignore
import type { V2Standard } from './v2-standard';

/**
 * 
 * @export
 * @interface V2ManagementCreateAssetRequest
 */
export interface V2ManagementCreateAssetRequest {
    /**
     * 
     * @type {V2Blockchain}
     * @memberof V2ManagementCreateAssetRequest
     */
    'blockchainId': V2Blockchain;
    /**
     * Contract address (empty for native assets)
     * @type {string}
     * @memberof V2ManagementCreateAssetRequest
     */
    'contractAddress'?: string;
    /**
     * Asset symbol
     * @type {string}
     * @memberof V2ManagementCreateAssetRequest
     */
    'symbol': string;
    /**
     * Asset name
     * @type {string}
     * @memberof V2ManagementCreateAssetRequest
     */
    'name'?: string;
    /**
     * Number of decimal places
     * @type {number}
     * @memberof V2ManagementCreateAssetRequest
     */
    'decimals'?: number;
    /**
     * 
     * @type {V2Standard}
     * @memberof V2ManagementCreateAssetRequest
     */
    'standard': V2Standard;
    /**
     * CoinGecko identifier for price data
     * @type {string}
     * @memberof V2ManagementCreateAssetRequest
     */
    'coingeckoId'?: string;
    /**
     * Whether the asset is enabled (default: true)
     * @type {boolean}
     * @memberof V2ManagementCreateAssetRequest
     */
    'enabled'?: boolean;
    /**
     * Whether the asset is vetted (default: false)
     * @type {boolean}
     * @memberof V2ManagementCreateAssetRequest
     */
    'vetted'?: boolean;
}



