/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2SortOrder } from './v2-sort-order';

/**
 * 
 * @export
 * @interface V2PaginationRequest
 */
export interface V2PaginationRequest {
    /**
     * Number of results per page (default 50, max 1000)
     * @type {number}
     * @memberof V2PaginationRequest
     */
    'pageSize'?: number;
    /**
     * Token for pagination from previous response
     * @type {string}
     * @memberof V2PaginationRequest
     */
    'pageToken'?: string;
    /**
     * Field to order results by
     * @type {string}
     * @memberof V2PaginationRequest
     */
    'orderBy'?: string;
    /**
     * 
     * @type {V2SortOrder}
     * @memberof V2PaginationRequest
     */
    'order'?: V2SortOrder;
}



