/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - QUORUM_STATE_CREATED: Freshly created, but no push notifications sent   - QUORUM_STATE_PENDING: Push notifications to member devices sent, but not all confirmed  - QUORUM_STATE_CONFIRMED: All devices have accepted membership  - QUORUM_STATE_REJECTED: 1+ Devices have rejected membership  - QUORUM_STATE_FAILED: Generic error state  - QUORUM_STATE_SUPER: FSM USE ONLY: Super state  - QUORUM_STATE_INITIAL: FSM USE ONLY: Initial state  - QUORUM_STATE_MODIFY_MEMBERSHIP: Register new quorum members here  - QUORUM_STATE_MODIFY_SHARDS: Key shards are being modified  - QUORUM_STATE_FINALIZE_MODIFICATION: Members finalize the quorum modification, ensuring old shards are deleted etc.
 * @export
 * @enum {string}
 */

export const V2QuorumState = {
    QuorumStateCreated: 'QUORUM_STATE_CREATED',
    QuorumStatePending: 'QUORUM_STATE_PENDING',
    QuorumStateConfirmed: 'QUORUM_STATE_CONFIRMED',
    QuorumStateRejected: 'QUORUM_STATE_REJECTED',
    QuorumStateFailed: 'QUORUM_STATE_FAILED',
    QuorumStateSuper: 'QUORUM_STATE_SUPER',
    QuorumStateInitial: 'QUORUM_STATE_INITIAL',
    QuorumStateModifyMembership: 'QUORUM_STATE_MODIFY_MEMBERSHIP',
    QuorumStateModifyShards: 'QUORUM_STATE_MODIFY_SHARDS',
    QuorumStateFinalizeModification: 'QUORUM_STATE_FINALIZE_MODIFICATION'
} as const;

export type V2QuorumState = typeof V2QuorumState[keyof typeof V2QuorumState];



