/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - SEARCH_TYPE_CONTAINS: Default substring search  - SEARCH_TYPE_STARTS_WITH: Prefix search  - SEARCH_TYPE_EXACT: Exact match  - SEARCH_TYPE_FUZZY: Fuzzy/similarity search  - SEARCH_TYPE_FULLTEXT: Full-text search (future)
 * @export
 * @enum {string}
 */

export const V2SearchType = {
    SearchTypeContains: 'SEARCH_TYPE_CONTAINS',
    SearchTypeStartsWith: 'SEARCH_TYPE_STARTS_WITH',
    SearchTypeExact: 'SEARCH_TYPE_EXACT',
    SearchTypeFuzzy: 'SEARCH_TYPE_FUZZY',
    SearchTypeFulltext: 'SEARCH_TYPE_FULLTEXT'
} as const;

export type V2SearchType = typeof V2SearchType[keyof typeof V2SearchType];



