/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V2Standard = {
    Native: 'NATIVE',
    Erc20: 'ERC20',
    IssuedCurrency: 'ISSUED_CURRENCY',
    Erc721: 'ERC721',
    Spl: 'SPL',
    Custom: 'CUSTOM'
} as const;

export type V2Standard = typeof V2Standard[keyof typeof V2Standard];



