/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2Blockchain } from './v2-blockchain';
// May contain unused imports in some cases
// @ts-ignore
import type { V2HydratedSweepAsset } from './v2-hydrated-sweep-asset';
// May contain unused imports in some cases
// @ts-ignore
import type { V2SweepFrequency } from './v2-sweep-frequency';
// May contain unused imports in some cases
// @ts-ignore
import type { V2SweepStatus } from './v2-sweep-status';
// May contain unused imports in some cases
// @ts-ignore
import type { V2VaultWalletIdentifier } from './v2-vault-wallet-identifier';

/**
 * 
 * @export
 * @interface V2SweepConfiguration
 */
export interface V2SweepConfiguration {
    /**
     * The sweep configuration ID
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'id': string;
    /**
     * The organization ID
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'organizationId': string;
    /**
     * The ID of the user who created this sweep configuration
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'createdBy': string;
    /**
     * The date and time the sweep configuration was created
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'createdAt': string;
    /**
     * The ID of the user who updated this sweep configuration
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'updatedBy': string;
    /**
     * The date and time the sweep configuration was updated
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'updatedAt': string;
    /**
     * The sweep configuration name
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'name': string;
    /**
     * The sweep configuration description
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'description'?: string;
    /**
     * 
     * @type {V2Blockchain}
     * @memberof V2SweepConfiguration
     */
    'blockchain': V2Blockchain;
    /**
     * 
     * @type {V2VaultWalletIdentifier}
     * @memberof V2SweepConfiguration
     */
    'feeWallet': V2VaultWalletIdentifier;
    /**
     * 
     * @type {V2VaultWalletIdentifier}
     * @memberof V2SweepConfiguration
     */
    'destinationWallet': V2VaultWalletIdentifier;
    /**
     * 
     * @type {V2SweepFrequency}
     * @memberof V2SweepConfiguration
     */
    'sweepFrequency': V2SweepFrequency;
    /**
     * The assets to sweep
     * @type {Array<V2HydratedSweepAsset>}
     * @memberof V2SweepConfiguration
     */
    'assets': Array<V2HydratedSweepAsset>;
    /**
     * 
     * @type {V2SweepStatus}
     * @memberof V2SweepConfiguration
     */
    'status': V2SweepStatus;
    /**
     * The date and time the sweep configuration was last executed
     * @type {string}
     * @memberof V2SweepConfiguration
     */
    'lastSwept'?: string;
    /**
     * Whether the sweep is currently running
     * @type {boolean}
     * @memberof V2SweepConfiguration
     */
    'sweepRunning': boolean;
}



