/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V2SessionState = {
    SessionStateCreated: 'SESSION_STATE_CREATED',
    SessionStatePending: 'SESSION_STATE_PENDING',
    SessionStateSubmitted: 'SESSION_STATE_SUBMITTED',
    SessionStateCompleted: 'SESSION_STATE_COMPLETED',
    SessionStateTimedOut: 'SESSION_STATE_TIMED_OUT',
    SessionStateFailed: 'SESSION_STATE_FAILED',
    SessionStateProcessed: 'SESSION_STATE_PROCESSED',
    SessionStateSuper: 'SESSION_STATE_SUPER',
    SessionStateInitial: 'SESSION_STATE_INITIAL'
} as const;

export type V2SessionState = typeof V2SessionState[keyof typeof V2SessionState];



