/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2SessionState } from './v2-session-state';
// May contain unused imports in some cases
// @ts-ignore
import type { V2SessionType } from './v2-session-type';

/**
 * 
 * @export
 * @interface V2Session
 */
export interface V2Session {
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'organizationId': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'membershipId': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'sessionSetId': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'createdBy': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'expiresAt': string;
    /**
     * 
     * @type {V2SessionType}
     * @memberof V2Session
     */
    'type': V2SessionType;
    /**
     * 
     * @type {boolean}
     * @memberof V2Session
     */
    'accepted': boolean;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'payloadId': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'devicePayload': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'notificationPayload': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'notificationTrigger': string;
    /**
     * 
     * @type {string}
     * @memberof V2Session
     */
    'notificationBody': string;
    /**
     * 
     * @type {V2SessionState}
     * @memberof V2Session
     */
    'state': V2SessionState;
}



