/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2SubscriptionConfig } from './v2-subscription-config';

/**
 * 
 * @export
 * @interface V2Subscription
 */
export interface V2Subscription {
    /**
     * The webhook subscription ID
     * @type {string}
     * @memberof V2Subscription
     */
    'id': string;
    /**
     * The webhook ID
     * @type {string}
     * @memberof V2Subscription
     */
    'webhookId': string;
    /**
     * The organization ID
     * @type {string}
     * @memberof V2Subscription
     */
    'organizationId': string;
    /**
     * The ID of the user who created this webhook
     * @type {string}
     * @memberof V2Subscription
     */
    'createdBy': string;
    /**
     * The date and time the webhook was created
     * @type {string}
     * @memberof V2Subscription
     */
    'createdAt': string;
    /**
     * The ID of the user who updated this webhook
     * @type {string}
     * @memberof V2Subscription
     */
    'updatedBy': string;
    /**
     * The date and time the webhook was updated
     * @type {string}
     * @memberof V2Subscription
     */
    'updatedAt': string;
    /**
     * 
     * @type {V2SubscriptionConfig}
     * @memberof V2Subscription
     */
    'config': V2SubscriptionConfig;
}

