/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V2SessionSetType = {
    SessionSetTypeQuorumCreation: 'SESSION_SET_TYPE_QUORUM_CREATION',
    SessionSetTypeKeyCreation: 'SESSION_SET_TYPE_KEY_CREATION',
    SessionSetTypeTxSignPool: 'SESSION_SET_TYPE_TX_SIGN_POOL',
    SessionSetTypeTxSignRequest: 'SESSION_SET_TYPE_TX_SIGN_REQUEST',
    SessionSetTypeQuorumJoin: 'SESSION_SET_TYPE_QUORUM_JOIN',
    SessionSetTypeQuorumModify: 'SESSION_SET_TYPE_QUORUM_MODIFY',
    SessionSetTypeQuorumModifyFinalize: 'SESSION_SET_TYPE_QUORUM_MODIFY_FINALIZE'
} as const;

export type V2SessionSetType = typeof V2SessionSetType[keyof typeof V2SessionSetType];



