/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - SESSION_SET_STATE_SUPER: FSM USE ONLY: Super state  - SESSION_SET_STATE_INITIAL: FSM USE ONLY: Initial state
 * @export
 * @enum {string}
 */

export const V2SessionSetState = {
    SessionSetStateCreated: 'SESSION_SET_STATE_CREATED',
    SessionSetStateInProgress: 'SESSION_SET_STATE_IN_PROGRESS',
    SessionSetStateComplete: 'SESSION_SET_STATE_COMPLETE',
    SessionSetStateTimedOut: 'SESSION_SET_STATE_TIMED_OUT',
    SessionSetStateFailed: 'SESSION_SET_STATE_FAILED',
    SessionSetStateSuper: 'SESSION_SET_STATE_SUPER',
    SessionSetStateInitial: 'SESSION_SET_STATE_INITIAL'
} as const;

export type V2SessionSetState = typeof V2SessionSetState[keyof typeof V2SessionSetState];



