/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2FuzzyMatch } from './v2-fuzzy-match';

/**
 * 
 * @export
 * @interface V2StringFilter
 */
export interface V2StringFilter {
    /**
     * Exact match
     * @type {string}
     * @memberof V2StringFilter
     */
    'eq'?: string;
    /**
     * Not equal to
     * @type {string}
     * @memberof V2StringFilter
     */
    'notEq'?: string;
    /**
     * Contains substring (case-insensitive)
     * @type {string}
     * @memberof V2StringFilter
     */
    'contains'?: string;
    /**
     * Starts with prefix (case-insensitive)
     * @type {string}
     * @memberof V2StringFilter
     */
    'startsWith'?: string;
    /**
     * Ends with suffix (case-insensitive)
     * @type {string}
     * @memberof V2StringFilter
     */
    'endsWith'?: string;
    /**
     * Value is in the list
     * @type {Array<string>}
     * @memberof V2StringFilter
     */
    'in'?: Array<string>;
    /**
     * Value is not in the list
     * @type {Array<string>}
     * @memberof V2StringFilter
     */
    'notIn'?: Array<string>;
    /**
     * Regular expression match
     * @type {string}
     * @memberof V2StringFilter
     */
    'regex'?: string;
    /**
     * Check if field is null
     * @type {boolean}
     * @memberof V2StringFilter
     */
    'isNull'?: boolean;
    /**
     * 
     * @type {V2FuzzyMatch}
     * @memberof V2StringFilter
     */
    'fuzzy'?: V2FuzzyMatch;
}

