/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V2User } from './v2-user';

/**
 * 
 * @export
 * @interface V2UpdateUserResponse
 */
export interface V2UpdateUserResponse {
    /**
     * 
     * @type {V2User}
     * @memberof V2UpdateUserResponse
     */
    'user'?: V2User;
}

