/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V2VaultTag
 */
export interface V2VaultTag {
    /**
     * The vault ID
     * @type {string}
     * @memberof V2VaultTag
     */
    'vaultId': string;
    /**
     * The tags belonging to the vault
     * @type {Array<string>}
     * @memberof V2VaultTag
     */
    'tags'?: Array<string>;
}

