/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const V2WalletLimitStatus = {
    LimitCreated: 'LIMIT_CREATED',
    LimitEnabled: 'LIMIT_ENABLED',
    LimitRejected: 'LIMIT_REJECTED',
    LimitDeleted: 'LIMIT_DELETED',
    LimitError: 'LIMIT_ERROR',
    LimitCreationApprovalPending: 'LIMIT_CREATION_APPROVAL_PENDING',
    LimitCreationApprovalComplete: 'LIMIT_CREATION_APPROVAL_COMPLETE',
    LimitDeletionApprovalPending: 'LIMIT_DELETION_APPROVAL_PENDING',
    LimitDeletionApprovalComplete: 'LIMIT_DELETION_APPROVAL_COMPLETE'
} as const;

export type V2WalletLimitStatus = typeof V2WalletLimitStatus[keyof typeof V2WalletLimitStatus];



