/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Commonv2Asset } from './commonv2-asset';
// May contain unused imports in some cases
// @ts-ignore
import type { V2LimitType } from './v2-limit-type';
// May contain unused imports in some cases
// @ts-ignore
import type { V2Matcher } from './v2-matcher';
// May contain unused imports in some cases
// @ts-ignore
import type { V2WalletLimitStatus } from './v2-wallet-limit-status';

/**
 * 
 * @export
 * @interface V2WalletLimit
 */
export interface V2WalletLimit {
    /**
     * The wallet limit policy ID
     * @type {string}
     * @memberof V2WalletLimit
     */
    'id': string;
    /**
     * The creator ID
     * @type {string}
     * @memberof V2WalletLimit
     */
    'createdBy': string;
    /**
     * The organization ID
     * @type {string}
     * @memberof V2WalletLimit
     */
    'organizationId': string;
    /**
     * The wallet ID
     * @type {string}
     * @memberof V2WalletLimit
     */
    'walletId': string;
    /**
     * The vault ID
     * @type {string}
     * @memberof V2WalletLimit
     */
    'vaultId': string;
    /**
     * The limit quantity
     * @type {string}
     * @memberof V2WalletLimit
     */
    'limitQty'?: string;
    /**
     * The limit duration
     * @type {string}
     * @memberof V2WalletLimit
     */
    'duration'?: string;
    /**
     * 
     * @type {V2LimitType}
     * @memberof V2WalletLimit
     */
    'limitType': V2LimitType;
    /**
     * The date and time the wallet limit policy was created
     * @type {string}
     * @memberof V2WalletLimit
     */
    'createdAt': string;
    /**
     * The date and time the wallet limit policy was updated
     * @type {string}
     * @memberof V2WalletLimit
     */
    'updatedAt': string;
    /**
     * 
     * @type {Commonv2Asset}
     * @memberof V2WalletLimit
     */
    'asset': Commonv2Asset;
    /**
     * 
     * @type {Array<V2Matcher>}
     * @memberof V2WalletLimit
     */
    'matchers'?: Array<V2Matcher>;
    /**
     * 
     * @type {V2WalletLimitStatus}
     * @memberof V2WalletLimit
     */
    'status': V2WalletLimitStatus;
    /**
     * Whether the limit is active
     * @type {boolean}
     * @memberof V2WalletLimit
     */
    'active': boolean;
}



