/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V2Webhook
 */
export interface V2Webhook {
    /**
     * The webhook ID.
     * @type {string}
     * @memberof V2Webhook
     */
    'id': string;
    /**
     * The organization ID
     * @type {string}
     * @memberof V2Webhook
     */
    'organizationId': string;
    /**
     * The ID of the user who created this webhook
     * @type {string}
     * @memberof V2Webhook
     */
    'createdBy': string;
    /**
     * The date and time the webhook was created
     * @type {string}
     * @memberof V2Webhook
     */
    'createdAt': string;
    /**
     * The ID of the user who updated this webhook
     * @type {string}
     * @memberof V2Webhook
     */
    'updatedBy': string;
    /**
     * The date and time the webhook was updated
     * @type {string}
     * @memberof V2Webhook
     */
    'updatedAt': string;
    /**
     * The webhook name
     * @type {string}
     * @memberof V2Webhook
     */
    'name': string;
    /**
     * The webhook description
     * @type {string}
     * @memberof V2Webhook
     */
    'description'?: string;
    /**
     * The webhook endpoint to send data to
     * @type {string}
     * @memberof V2Webhook
     */
    'endpoint': string;
    /**
     * The number of subscriptions associated with the webhook
     * @type {number}
     * @memberof V2Webhook
     */
    'subscriptionCount': number;
    /**
     * The public key used to verify the webhook signature
     * @type {string}
     * @memberof V2Webhook
     */
    'publicKey': string;
    /**
     * The timestamp of the last successful webhook delivery
     * @type {string}
     * @memberof V2Webhook
     */
    'lastSuccess'?: string;
    /**
     * The timestamp of the last failed webhook delivery
     * @type {string}
     * @memberof V2Webhook
     */
    'lastFailure'?: string;
    /**
     * The number of successful webhook deliveries in the last hour
     * @type {number}
     * @memberof V2Webhook
     */
    'successCount': number;
    /**
     * The number of failed webhook deliveries in the last hour
     * @type {number}
     * @memberof V2Webhook
     */
    'failureCount': number;
}

