/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V2WalletBalance
 */
export interface V2WalletBalance {
    /**
     * The wallet ID that the connection is associated with
     * @type {string}
     * @memberof V2WalletBalance
     */
    'walletId'?: string;
    /**
     * The aggregated fiat value of the wallet
     * @type {string}
     * @memberof V2WalletBalance
     */
    'aggregatedFiatValue'?: string;
}

