/* tslint:disable */
/* eslint-disable */
/**
 * Palisade API
 * The Palisade API enables programmatic interaction with the various features of the Palisade platform
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VaultServiceUpdateVaultRequest
 */
export interface VaultServiceUpdateVaultRequest {
    /**
     * The name of the vault
     * @type {string}
     * @memberof VaultServiceUpdateVaultRequest
     */
    'name': string;
    /**
     * The description of the vault
     * @type {string}
     * @memberof VaultServiceUpdateVaultRequest
     */
    'description'?: string;
    /**
     * Correlation ID for tracking various actions on the vault
     * @type {string}
     * @memberof VaultServiceUpdateVaultRequest
     */
    'correlationId'?: string;
}

